### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by abhi1693** [cognalys/Cogdemov2#1]
Application is crashing while verifying mobile number. I'm using `Android Studio 0.5.2` and I've imported the library provided with the code.

```
05-17 09:08:52.910    1186-1186/com.text.me E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.text.me, PID: 1186
    java.lang.NoClassDefFoundError: com.matesnetwork.Cognalys.R$layout
            at com.matesnetwork.Cognalys.VerifyMobile.onCreate(VerifyMobile.java:81)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by abhi1693** [comment]
I have finally made the library to work in `Android Studio`. I don't receive any calls although the verification api is executed successfully. The same happens with the application that I had downloaded from play store. Can you tell me why this happens?

**Comment by cognalys** [comment]
Which mobile number u have tried ?

**Comment by abhi1693** [comment]
I have a Tata Docomo number (Maharashtra Circle).

**Comment by cognalys** [comment]
Please follow below steps and reply . what happens 

Step1 :

Create an OTP app and grab YOUR_OTP_ACCESS_TOKEN , YOUR_OTP_APP_ID

then hit from browser 

https://www.cognalys.com/api/v1/otp/?app_id=YOUR_OTP_APP_ID&access_token=YOUR_OTP_ACCESS_TOKEN&mobile=MOBILE
it will generate a missed call to the requested mobile number . And return a keymatch (to authenticate step 2 ) and otp_start ( the first five digits of the missed call number )

Step 2 :

then hit from browser 

https://www.cognalys.com/api/v1/otp/confirm/?app_id=YOUR_OTP_APP_ID&access_token=YOUR_OTP_ACCESS_TOKEN&keymatch=KEYMATCH&otp=OTP
Ask your user to enter the last five digit of the missed call number concatenate otp_start and last five digit for parameter otp and hit the API including keymatch

**Comment by abhi1693** [comment]
![image](https://cloud.githubusercontent.com/assets/5083532/7720852/9e5e1a5a-feef-11e4-9866-8917e24f7830.png)

**Comment by cognalys** [comment]
Please remove %20 ( space) before &mobile parameter.

**Comment by abhi1693** [comment]
Yeah, I figured that out. Sorry, my bad! I got the call. Why doesn't it work with the Android Application?

**Comment by ashishrajani** [comment]
i am getting the same error, how did you fixed the android studio configuration.

**Comment by casusapp** [comment]
how did you fixed it?? please help

**Comment by MopideviAshok** [comment]
I am also getting same issue. How did you fix it in Android Studio

**Comment by abhi1693** [comment]
I couldn't get it fixed, so I created my own demo.

**Comment by ankur2210** [comment]
pplication is crashing while verifying mobile number. I'm using latest Android Studio and I've imported the library provided with the code.

05-17 09:08:52.910    1186-1186/com.text.me E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.text.me, PID: 1186
    java.lang.NoClassDefFoundError: com.matesnetwork.Cognalys.R$layout
            at com.matesnetwork.Cognalys.VerifyMobile.onCreate(VerifyMobile.java:81)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.
