### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by madhu2b4u** [cognalys/Cogdemov2#5]
Application is crashing while verify phone number
Android Studio 2.1.1  

Please provide the solution for this ! Thank you

E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.text.me, PID: 1186
    java.lang.NoClassDefFoundError: com.matesnetwork.Cognalys.R$layout
            at com.matesnetwork.Cognalys.VerifyMobile.onCreate(VerifyMobile.java:81)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by harshvishu** [comment]
I think you are integrating the library the wrong way.

If your are trying to use Cognalys.jar directl, I think that is not the correct way.

> Follow this procedure
> 1. Download the source code of the repo.
> 2. Import the 'Cognalys' as module in your project
> 3. add `compile project(':cognalys')` in your app level gradle
> **Note**: in your settings.gradle `include ':cognalys'` should be present.
1. If your gradle generates error/issues related to Manifest merger
   add `tools:replace="android:theme,android:icon"` inside application tag of your manifest file.

**Comment by ghost** [comment]
I tried this way  but I am getting this Error:Configuration with name 'default' not found. can you please help me @harshvishu @cognalys
